### ISSUE TITLE
virtblock mounts as fuse

### ISSUE THREAD

**Issue by JohnStrunk** [gluster/gluster-csi-driver#167]
**Describe the bug**
During testing for GCS 1.0-pre, I attempted to use the virtblock csi driver. The result was a fuse-based mount in the container, not an xfs formatted loopback device.

**Steps to reproduce**
Use the following yaml:
```yaml
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-glustervirtblock
spec:
  storageClassName: glustervirtblock-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: batch/v1
kind: Job
metadata:
  name: fs-performance
spec:
  template:
    metadata:
      name: fs-performance
    spec:
      containers:
        - name: fio
          image: quay.io/johnstrunk/fs-performance:latest
          args: ["clone", "kernel"]
          env:
            - name: TARGET_CAPACITY_MB
              value: "500"
            - name: TARGET_PATH
              value: "/target"
            - name: CLONE_REPO
              value: "https://github.com/gluster/glusterfs.git"
          volumeMounts:
            - name: target
              mountPath: /target
      restartPolicy: Never
      volumes:
        - name: target
          persistentVolumeClaim:
            claimName: test-glustervirtblock
```

**Actual results**
Exec into the running pod and take a look at the mount:
```
$ kubectl --kubeconfig=kubeconfig -n test exec -it fs-performance-4mvv8 bash
[bench-runner@fs-performance-4mvv8 /]$ df -h
Filesystem                                                                               Size  Used Avail Use% Mounted on
overlay                                                                                   27G  5.7G   22G  22% /
tmpfs                                                                                    920M     0  920M   0% /dev
tmpfs                                                                                    920M     0  920M   0% /sys/fs/cgroup
gluster-kube3-0.glusterd2.gcs:block_hosting_volume_dd8b1b81-4475-42fb-9467-d6de9c1dbe42  5.0G  438M  4.6G   9% /target
/dev/mapper/atomicos-root                                                                 27G  5.7G   22G  22% /etc/hosts
shm                                                                                       64M     0   64M   0% /dev/shm
tmpfs                                                                                    920M   12K  920M   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs                                                                                    920M     0  920M   0% /proc/acpi
tmpfs                                                                                    920M     0  920M   0% /proc/scsi
tmpfs                                                                                    920M     0  920M   0% /sys/firmware
[bench-runner@fs-performance-4mvv8 /]$ grep target /proc/mounts 
gluster-kube3-0.glusterd2.gcs:block_hosting_volume_dd8b1b81-4475-42fb-9467-d6de9c1dbe42 /target fuse.glusterfs rw,relatime,user_id=0,group_id=0,default_permissions,allow_other,max_read=131072 0 0
```

**Expected behavior**
`/target` is of type `fuse.glusterfs` not `xfs` as would be expected

**Additional context**
